package com.example.crm.infrastructure.web.config

import io.swagger.v3.oas.models.OpenAPI
import io.swagger.v3.oas.models.info.Info
import io.swagger.v3.oas.models.Components
import io.swagger.v3.oas.models.security.SecurityScheme
import io.swagger.v3.oas.models.security.SecurityRequirement
import io.swagger.v3.oas.models.parameters.RequestBody
import io.swagger.v3.oas.models.media.Content
import io.swagger.v3.oas.models.media.MediaType
import io.swagger.v3.oas.models.media.Schema
import io.swagger.v3.oas.models.PathItem
import io.swagger.v3.oas.models.Operation
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration

@Configuration
class OpenApiConfig {

    @Bean
    fun customOpenAPI(): OpenAPI {
        // Add a bearer authentication scheme so Swagger UI knows about the security scheme
        val bearerScheme = SecurityScheme()
            .type(SecurityScheme.Type.HTTP)
            .scheme("bearer")
            .bearerFormat("JWT")

        val openApi = OpenAPI()
            .components(Components().addSecuritySchemes("bearerAuth", bearerScheme))
            .addSecurityItem(SecurityRequirement().addList("bearerAuth"))
            .info(
                Info()
                    .title("CRM API")
                    .version("v1")
                    .description("Swagger UI for CRM API")
            )

        // Add a lightweight requestBody example for the auth token operation so
        // Swagger UI shows the example request body. We add only the example; the
        // full set of paths is still generated by springdoc at runtime.
        try {
            val schema: Schema<Any> = Schema()
            schema.example = mapOf("email" to "admin@saas.com", "password" to "string")
            val media = MediaType().schema(schema)
            val content = Content().addMediaType("application/json", media)
            val rb = RequestBody().content(content)
            val op = Operation().requestBody(rb)
            val pathItem = PathItem().post(op)
            openApi.path("/api/v1/auth/token", pathItem)
        } catch (_: Exception) {
            // ignore if something goes wrong here; don't break startup
        }

        return openApi
    }

    // Keep OpenAPI bean minimal; adding request examples dynamically can be brittle
    // across springdoc versions. We add the example via the static swagger-auth.js
    // script which pre-fills the login form client-side.

    // We add a lightweight auth path example in the main OpenAPI bean above.

    
}
