spring:
  application:
    name: crm

  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: crm
    password: crm
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
      group:
        readiness:
          additional-path: server:/readyz
        liveness:
          additional-path: server:/livez
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

# Configure springdoc swagger-ui to include our extra script
springdoc:
  swagger-ui:
    init-oauth: false
    urls: []
    # add our custom JS to be loaded by Swagger UI
    url:
    additional-scripts:
      - /swagger-ui/swagger-auth.js

app:
  cors:
    # aceita frontend local e subdominios luizlab
    allowed-origin-patterns: http://localhost:*,http://127.0.0.1:*,https://*.luizlab.com,http://*.luizlab.com
