spring:
  application:
    name: crm

  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: crm
    password: crm
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

